import {
  CREATE_ACTOR,
  CREATE_MOVIE_SHOW,
  CREATE_REVIEW,
  CREATE_USER,
  DELETE_ACTOR,
  DELETE_MOVIE_SHOW,
  DELETE_USER,
  READ_ACTOR,
  READ_ALL_ACTOR,
  READ_ALL_MOVIE_SHOW,
  READ_ALL_REVIEW,
  READ_ALL_USER,
  READ_MOVIE_SHOW,
  READ_USER,
  UPDATE_ACTOR,
  UPDATE_MOVIE_SHOW,
  UPDATE_USER,
} from './permission.const';

export const admin = [
  CREATE_ACTOR,
  READ_ALL_ACTOR,
  READ_ACTOR,
  UPDATE_ACTOR,
  DELETE_ACTOR,
  READ_ALL_USER,
  READ_USER,
  DELETE_USER,
  CREATE_MOVIE_SHOW,
  READ_ALL_MOVIE_SHOW,
  READ_MOVIE_SHOW,
  UPDATE_MOVIE_SHOW,
  DELETE_MOVIE_SHOW,
];

export const user = [
  READ_ALL_ACTOR,
  READ_ACTOR,
  CREATE_USER,
  UPDATE_USER,
  CREATE_REVIEW,
  READ_ALL_REVIEW,
];
